Prefix bug
pestphp/pest-plugin-arch pull request #7
Opened 2023-10-06 08:06 UTC by Katalam

Basically what happend here https://github.com/pestphp/pest/issues/966 was that the plugin created directories with the path `Core/lication/Contracts` instead of `Core/Application/Contracts` with the given code
```php
test('app')
    ->expect('App\Core\Application\Contracts')
    ->toBeClasses();
```
And passed because no File was found

2023-10-10 13:48 UTC, devajmeireles approved these changes

2023-10-10 13:49 UTC, Katalam commented
@devajmeireles The test problem does not sound like a problem on my side, can you have a look at it?

2023-10-10 15:51 UTC, nunomaduro requested changes

2023-10-10 15:51 UTC, nunomaduro commented on src/Repositories/ObjectsRepository.php
> +                $nameWithoutPrefix = $posFirstPrefix !== false ? substr($name, $posFirstPrefix + strlen($prefix)) : $name;
Can you first create a test - that fails prior to this change?

2024-04-03 21:02 UTC, Katalam commented on src/Repositories/ObjectsRepository.php
> +                $nameWithoutPrefix = $posFirstPrefix !== false ? substr($name, $posFirstPrefix + strlen($prefix)) : $name;
Tbh I don't really know how to do it, the linked issue shows a problematic environment and I don't know how I create a test case that will use a logic that I overwrite within the same branch

2024-09-09 15:35 UTC, wimulkeman commented
@nunomaduro Can I contribute with something to help getting this PR merged?

Is it primarily hanging on the test with the incorrect working before the fix applied in the PR?

2025-03-30 17:27 UTC, merged