[2.x] Add `arch` test function
pestphp/pest-plugin-arch pull request #9
Opened 2023-11-28 14:01 UTC by lukeraymonddowning

Adds a new `arch` function that is a synonym for `test()->group('arch')`. This allows users to easily isolate arch tests for inclusion/exclusion when running their test suite. 

```php
// Before
it('tests my controllers', function () {
  expect('App\Http\Controllers')->toUseStrictTypes();
});

// After
arch('controllers use strict types', function () {
  expect('App\Http\Controllers')->toUseStrictTypes();
});
```

If we promote this way of declaring arch tests as the "standard" (in documentation/demos etc), it will allow us to rely on this feature in other tooling (such as mutation testing) to automatically exclude/include architecture tests as required.

It also allows us to add to this function for other cool integrations down the line as we see fit.

One consideration is that currently the PHPStorm plugin does not include support for running functions starting with `arch`, but as it is open source we could PR that if we want to go ahead with this 👍

2023-11-28 14:05 UTC, nunomaduro requested changes

2023-11-28 14:05 UTC, nunomaduro commented on src/Autoload.php
> +        return it($description, $closure)->group('arch');
this should call `test` instead.

2023-11-28 14:09 UTC, lukeraymonddowning commented on src/Autoload.php
> +        return it($description, $closure)->group('arch');
Updated

2023-12-04 20:03 UTC, lukeraymonddowning commented
I've updated the PR to add support for `--arch` and `--exclude-arch`, which is basically shorthand for `--group=arch` and `--exclude-group=arch` respectively.

2023-12-05 18:56 UTC, merged